import Icon from '@ant-design/icons';
import React from 'react';

import { icon as at } from './components/icons/at-solid';
import { icon as bong } from './components/icons/bong-solid';
import { icon as openBox } from './components/icons/box-open-solid';
import { icon as medicalBriefcase } from './components/icons/briefcase-medical-solid';
import { icon as bullhorn } from './components/icons/bullhorn-solid';
import { icon as calendar } from './components/icons/calendar-alt-solid';
import { icon as calendarChecked } from './components/icons/calendar-check-solid';
import { icon as medicalPills } from './components/icons/category';
import { icon as settings } from './components/icons/cogs-solid';
import { icon as copy } from './components/icons/copy-solid';
import { icon as creditCard } from './components/icons/credit-card-solid';
import { icon as desktop } from './components/icons/desktop-solid';
import { icon as dollar } from './components/icons/dollor';
import { icon as cartDolly } from './components/icons/dolly-solid';
import { icon as edit } from './components/icons/edit-solid';
import { icon as mail } from './components/icons/envelope-open-solid';
import { icon as externalLink } from './components/icons/external-link-alt-solid';
import { icon as eyeSlash } from './components/icons/eye-slash-solid';
import { icon as eye } from './components/icons/eye-solid';
import { icon as fileGeneral } from './components/icons/file-alt-solid';
import { icon as fileAudio } from './components/icons/file-audio-solid';
import { icon as fileImage } from './components/icons/file-image-solid';
import { icon as filePdf } from './components/icons/file-pdf-solid';
import { icon as filePrescription } from './components/icons/file-prescription-solid';
import { icon as fileVideo } from './components/icons/file-video-solid';
import { icon as filter } from './components/icons/filter-solid';
import { icon as heartBeat } from './components/icons/heartbeat-solid';
import { icon as home } from './components/icons/home-solid';
import { icon as userMedical } from './components/icons/hospital-user-solid';
import { icon as mailBulk } from './components/icons/mail-bulk-solid';
import { icon as mapMarked } from './components/icons/map-marked-alt-solid';
import { icon as mapMarker } from './components/icons/map-marker-alt-solid';
import { icon as mapPin } from './components/icons/map-pin-solid';
import { icon as medical } from './components/icons/medical';
import { icon as medikit } from './components/icons/medkit-solid';
import { icon as moneyBill } from './components/icons/money-bill-alt-solid';
import { icon as moneyBillWave } from './components/icons/money-bill-wave-solid';
import { icon as moneyChecked } from './components/icons/money-check-solid';
import { icon as moneyWave } from './components/icons/money-wave';
import { icon as medicalNotes } from './components/icons/notes-medical-solid';
import { icon as palette } from './components/icons/palette-solid';
import { icon as medicalBottle } from './components/icons/prescription-bottle-alt-solid';
import { icon as prescription } from './components/icons/prescription-solid';
import { icon as reciept } from './components/icons/reciept';
import { icon as rupee } from './components/icons/rupee';
import { icon as search } from './components/icons/search-solid';
import { icon as shippingFast } from './components/icons/shipping-fast-solid';
import { icon as stockAdjustment } from './components/icons/stock-adjustment';
import { icon as store } from './components/icons/store-solid';
import { icon as trash } from './components/icons/trash-alt-solid';
import { icon as truckLoading } from './components/icons/truck-loading-solid';
import { icon as user } from './components/icons/user-solid';
import { icon as userCheck } from './components/icons/user-check-solid';
import { icon as userEdit } from './components/icons/user-edit-solid';
import { icon as userDoctor } from './components/icons/user-md-solid';
import { icon as userDelete } from './components/icons/user-minus-solid';
import { icon as userNurse } from './components/icons/user-nurse-solid';
import { icon as userAdd } from './components/icons/user-plus-solid';
import { icon as userRemove } from './components/icons/user-times-solid';

export const AtIcon = (props: any) => <Icon component={at} {...props}></Icon>;
export const BongIcon = (props: any) => <Icon component={bong} {...props}></Icon>;
export const OpenBoxIcon = (props: any) => <Icon component={openBox} {...props}></Icon>;
export const MedicalBriefcaseIcon = (props: any) => <Icon component={medicalBriefcase} {...props}></Icon>;
export const BullhornIcon = (props: any) => <Icon component={bullhorn} {...props}></Icon>;
export const CalendarIcon = (props: any) => <Icon component={calendar} {...props}></Icon>;
export const CalendarCheckedIcon = (props: any) => <Icon component={calendarChecked} {...props}></Icon>;
export const MedicalPillsIcon = (props: any) => <Icon component={medicalPills} {...props}></Icon>;
export const SettingsIcon = (props: any) => <Icon component={settings} {...props}></Icon>;
export const CopyIcon = (props: any) => <Icon component={copy} {...props}></Icon>;
export const CrediCardIcon = (props: any) => <Icon component={creditCard} {...props}></Icon>;
export const DesktopIcon = (props: any) => <Icon component={desktop} {...props}></Icon>;
export const DollarIcon = (props: any) => <Icon component={dollar} {...props}></Icon>;
export const CartIcon = (props: any) => <Icon component={cartDolly} {...props}></Icon>;
export const EditIcon = (props: any) => <Icon component={edit} {...props}></Icon>;
export const MailIcon = (props: any) => <Icon component={mail} {...props}></Icon>;
export const ExternalLinkIcon = (props: any) => <Icon component={externalLink} {...props}></Icon>;
export const EyeSlashIcon = (props: any) => <Icon component={eyeSlash} {...props}></Icon>;
export const EyeIcon = (props: any) => <Icon component={eye} {...props}></Icon>;
export const FileIcon = (props: any) => <Icon component={fileGeneral} {...props}></Icon>;
export const AudioFileIcon = (props: any) => <Icon component={fileAudio} {...props}></Icon>;
export const ImageFileIcon = (props: any) => <Icon component={fileImage} {...props}></Icon>;
export const PdfFileIcon = (props: any) => <Icon component={filePdf} {...props}></Icon>;
export const PrescriptionFileIcon = (props: any) => <Icon component={filePrescription} {...props}></Icon>;
export const VideoFileIcon = (props: any) => <Icon component={fileVideo} {...props}></Icon>;
export const FilterIcon = (props: any) => <Icon component={filter} {...props}></Icon>;
export const HeartBeatIcon = (props: any) => <Icon component={heartBeat} {...props}></Icon>;
export const HomeIcon = (props: any) => <Icon component={home} {...props}></Icon>;
export const MedicalUserIcon = (props: any) => <Icon component={userMedical} {...props}></Icon>;
export const BulkMailIcon = (props: any) => <Icon component={mailBulk} {...props}></Icon>;
export const MapMarkedIcon = (props: any) => <Icon component={mapMarked} {...props}></Icon>;
export const MapMarkerIcon = (props: any) => <Icon component={mapMarker} {...props}></Icon>;
export const MapPinIcon = (props: any) => <Icon component={mapPin} {...props}></Icon>;
export const MedicalIcon = (props: any) => <Icon component={medical} {...props}></Icon>;
export const MedikitIcon = (props: any) => <Icon component={medikit} {...props}></Icon>;
export const MoneyBillIcon = (props: any) => <Icon component={moneyBill} {...props}></Icon>;
export const MoneyBillWaveIcon = (props: any) => <Icon component={moneyBillWave} {...props}></Icon>;
export const MoneyCheckedIcon = (props: any) => <Icon component={moneyChecked} {...props}></Icon>;
export const MoneyWaveIcon = (props: any) => <Icon component={moneyWave} {...props}></Icon>;
export const MedicalNoteIcon = (props: any) => <Icon component={medicalNotes} {...props}></Icon>;
export const PaletteIcon = (props: any) => <Icon component={palette} {...props}></Icon>;
export const MedicalBottleIcon = (props: any) => <Icon component={medicalBottle} {...props}></Icon>;
export const PrescriptionIcon = (props: any) => <Icon component={prescription} {...props}></Icon>;
export const RecieptIcon = (props: any) => <Icon component={reciept} {...props}></Icon>;
export const RupeeIcon = (props: any) => <Icon component={rupee} {...props}></Icon>;
export const SearchIcon = (props: any) => <Icon component={search} {...props}></Icon>;
export const ShippingIcon = (props: any) => <Icon component={shippingFast} {...props}></Icon>;
export const StockAdjustmentIcon = (props: any) => <Icon component={stockAdjustment} {...props}></Icon>;
export const StoreIcon = (props: any) => <Icon component={store} {...props}></Icon>;
export const TrashIcon = (props: any) => <Icon component={trash} {...props}></Icon>;
export const TruckLoadingIcon = (props: any) => <Icon component={truckLoading} {...props}></Icon>;
export const UserIcon = (props: any) => <Icon component={user} {...props}></Icon>;
export const UserOKIcon = (props: any) => <Icon component={userCheck} {...props}></Icon>;
export const EditUserIcon = (props: any) => <Icon component={userEdit} {...props}></Icon>;
export const DoctorIcon = (props: any) => <Icon component={userDoctor} {...props}></Icon>;
export const DeleteUserIcon = (props: any) => <Icon component={userDelete} {...props}></Icon>;
export const NurseIcon = (props: any) => <Icon component={userNurse} {...props}></Icon>;
export const AddUserIcon = (props: any) => <Icon component={userAdd} {...props}></Icon>;
export const RemoveUserIcon = (props: any) => <Icon component={userRemove} {...props}></Icon>;
