const permissions = require('./AdminPermissions').AdminPermissions;
export const Roles = [
  {
    Role: 'Admin',
    ID: 1,
    Permissions: [
      permissions.Dashborad,
      permissions.CalendarInDashboard,
      permissions.Patients,
      permissions.AddPatients,
      permissions.EditPatients,
      permissions.ViewPatient,
      permissions.DeletePatient,
      permissions.ViewPatientRecords,
      permissions.EditPatientRecords,
      permissions.Appointments,
      permissions.AddAppointments,
      permissions.EditAppointments,
      permissions.ViewAppointments,
      permissions.DeleteAppointments,
      permissions.Prescription,
      permissions.AddPrescription,
      permissions.EditPrescription,
      permissions.DeletePrescription,
      permissions.ViewPrescription,
      permissions.Invoice,
      permissions.AddInvoice,
      permissions.EditInvoice,
      permissions.DeleteInvoice,
      permissions.ViewInvoice,
      permissions.Request,
      permissions.AddRequest,
      permissions.EditRequest,
      permissions.DeleteRequest,
      permissions.ViewRequest,
      permissions.Bill,
      permissions.AddBill,
      permissions.EditBill,
      permissions.DeleteBill,
      permissions.ViewBill,
      permissions.Purchase,
      permissions.AddPurchase,
      permissions.EditPurchase,
      permissions.DeletePurchase,
      permissions.ViewPurchase,
      permissions.Stock,
      permissions.DeleteStock,
      permissions.Medicine,
      permissions.AddMedicine,
      permissions.EditMedicine,
      permissions.DeleteMedicine,
      permissions.ViewMedicine,
      permissions.MedicineCategory,
      permissions.AddMedicineCategory,
      permissions.EditMedicineCategory,
      permissions.DeleteMedicineCategory,
      permissions.Doctor,
      permissions.AddDoctor,
      permissions.EditDoctor,
      permissions.DeleteDoctor,
      permissions.ViewDoctor,
      permissions.Expense,
      permissions.AddExpense,
      permissions.EditExpense,
      permissions.DeleteExpense,
      permissions.ViewExpense,
      permissions.User,
      permissions.AddUser,
      permissions.EditUser,
      permissions.DeleteUser,
      permissions.ViewUser,
      permissions.Tax,
      permissions.AddTax,
      permissions.EditTax,
      permissions.DeleteTax,
      permissions.PaymentMethod,
      permissions.AddPaymentMethod,
      permissions.EditPaymentMethod,
      permissions.DeletePaymentMethod,
      permissions.ClinicalNotes,
      permissions.AddClinicalNotes,
      permissions.EditClinicalNotes,
      permissions.DeleteClinicalNotes,
      permissions.SystemInfo,
    ],
  },
  {
    Role: 'Doctor',
    ID: 2,
    Permissions: [
      permissions.Dashborad,
      permissions.CalendarInDashboard,
      permissions.Patients,
      permissions.AddPatients,
      permissions.EditPatients,
      permissions.ViewPatient,
      permissions.DeletePatient,
      permissions.EditPatientRecords,
      permissions.ViewPatientRecords,
      permissions.AddAppointments,
      permissions.EditAppointments,
      permissions.ViewAppointments,
      permissions.DeleteAppointments,
      permissions.Appointments,
      permissions.Prescription,
      permissions.AddPrescription,
      permissions.EditPrescription,
      permissions.ViewPrescription,
      permissions.DeletePrescription,
      permissions.Invoice,
      permissions.AddInvoice,
      permissions.EditInvoice,
      permissions.DeleteInvoice,
      permissions.ViewInvoice,
      permissions.Medicine,
      permissions.Doctor,
      permissions.EditDoctor,
      permissions.Expense,
      permissions.AddExpense,
      permissions.EditExpense,
      permissions.ViewExpense,
      permissions.DeleteExpense,
      permissions.ClinicalNotes,
      permissions.AddClinicalNotes,
      permissions.EditClinicalNotes,
    ],
  },
  {
    Role: 'Pharmacist',
    ID: 3,
    Permissions: [
      permissions.Dashborad,
      permissions.Bill,
      permissions.AddBill,
      permissions.EditBill,
      permissions.DeleteBill,
      permissions.ViewBill,
      permissions.Purchase,
      permissions.AddPurchase,
      permissions.EditPurchase,
      permissions.ViewPurchase,
      permissions.DeletePurchase,
      permissions.Stock,
      permissions.DeleteStock,
      permissions.Medicine,
      permissions.AddMedicine,
      permissions.EditMedicine,
      permissions.ViewMedicine,
      permissions.DeleteMedicine,
      permissions.MedicineCategory,
      permissions.AddMedicineCategory,
      permissions.EditMedicineCategory,
      permissions.DeleteMedicineCategory,
      permissions.Expense,
      permissions.AddExpense,
      permissions.EditExpense,
      permissions.DeleteExpense,
      permissions.ViewExpense,
      permissions.Tax,
      permissions.PaymentMethod,
    ],
  },
  {
    Role: 'Employee',
    ID: 4,
    Permissions: [permissions.Appointments, permissions.Invoice, permissions.Request, permissions.EditRequest, permissions.Expense],
  },
  {
    Role: 'PRO',
    ID: 5,
    Permissions: [
      permissions.Dashborad,
      permissions.Patients,
      permissions.AddPatients,
      permissions.Appointments,
      permissions.AddAppointments,
      permissions.Invoice,
      permissions.AddInvoice,
      permissions.EditInvoice,
      permissions.ViewInvoice,
      permissions.Request,
      permissions.EditRequest,
      permissions.AddRequest,
      permissions.ViewRequest,
      permissions.DeleteRequest,
    ],
  },
  {
    Role: 'Accountant',
    ID: 6,
    Permissions: [],
  },
];
export const users = [
  {
    ID: 1,
    UserName: 'paul_george',
    Password: '1234',
    Email: 'paul@george.com',
    UserRole: 1,
  },
];
