export const Patients = [
  {
    ID: 1,
    FirstName: 'Charlean',
    LastName: 'Heinrici',
    MobileNumber: '+93 887 509 0973',
    BloodGroup: 'O-',
    Email: 'cheinrici0@imageshack.us',
    DateOfBirth: new Date('06-Jun-2001'),
    Gender: 'Female',
    AddressLine1: '331 Goodland Circle',
    AddressLine2: '1 Bay Trail',
    City: 'Brengkok',
    Country: 'Indonesia',
    ZipCode: null,
    CreatedDate: new Date('18-Apr-1952'),
    Status: 'Active',
    MedicalHistory: {
      Diabetes: false,
      HeartProblems: true,
      KidneyStones: false,
      Cancer: false,
      Pregnancy: true,
      HighBloodPressure: false,
      Asthma: true,
      Jaundice: true,
      HIV_AIDS: true,
      BloodThinners: false,
      HighCholestrol: false,
      KidneyDisease: true,
      RheumaticFever: false,
      Epilepsy: true,
      OtherHistory:
        'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.',
    },
  },
  {
    ID: 2,
    FirstName: 'Wadsworth',
    LastName: 'Laverock',
    MobileNumber: '+51 101 050 2010',
    BloodGroup: 'AB-',
    Email: 'wlaverock1@reddit.com',
    DateOfBirth: new Date('13-Oct-1950'),
    Gender: 'Male',
    AddressLine1: '2190 Reindahl Plaza',
    AddressLine2: '0 Cambridge Point',
    City: 'Pasirreungit',
    Country: 'Indonesia',
    ZipCode: null,
    CreatedDate: new Date('27-Jan-1964'),
    Status: 'Active',
    MedicalHistory: {
      Diabetes: false,
      HeartProblems: true,
      KidneyStones: false,
      Cancer: false,
      Pregnancy: false,
      HighBloodPressure: false,
      Asthma: true,
      Jaundice: true,
      HIV_AIDS: false,
      BloodThinners: false,
      HighCholestrol: false,
      KidneyDisease: false,
      RheumaticFever: true,
      Epilepsy: true,
      OtherHistory: 'Mauris sit amet eros.',
    },
  },
  {
    ID: 3,
    FirstName: 'Robby',
    LastName: 'Maun',
    MobileNumber: '+23 034 167 9675',
    BloodGroup: 'B+',
    Email: 'rmaun2@utexas.edu',
    DateOfBirth: new Date('22-Feb-2005'),
    Gender: 'Female',
    AddressLine1: '15544 7th Point',
    AddressLine2: '94 Blackbird Terrace',
    City: 'Qingshanhu',
    Country: 'China',
    ZipCode: null,
    CreatedDate: new Date('01-Jul-1966'),
    Status: 'Active',
    MedicalHistory: {
      Diabetes: false,
      HeartProblems: false,
      KidneyStones: false,
      Cancer: true,
      Pregnancy: true,
      HighBloodPressure: true,
      Asthma: true,
      Jaundice: true,
      HIV_AIDS: false,
      BloodThinners: false,
      HighCholestrol: false,
      KidneyDisease: true,
      RheumaticFever: true,
      Epilepsy: false,
      OtherHistory: 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.',
    },
  },
  {
    ID: 4,
    FirstName: 'Dannie',
    LastName: 'MacGiffin',
    MobileNumber: '+87 319 476 6769',
    BloodGroup: 'A+',
    Email: 'dmacgiffin3@unblog.fr',
    DateOfBirth: new Date('22-Nov-1958'),
    Gender: 'Male',
    AddressLine1: '49941 Cascade Way',
    AddressLine2: '55 John Wall Plaza',
    City: 'Pampamarca',
    Country: 'Peru',
    ZipCode: null,
    CreatedDate: new Date('17-Jun-1977'),
    Status: 'Active',
    MedicalHistory: {
      Diabetes: false,
      HeartProblems: true,
      KidneyStones: true,
      Cancer: false,
      Pregnancy: false,
      HighBloodPressure: true,
      Asthma: false,
      Jaundice: true,
      HIV_AIDS: false,
      BloodThinners: false,
      HighCholestrol: true,
      KidneyDisease: true,
      RheumaticFever: false,
      Epilepsy: false,
      OtherHistory: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.',
    },
  },
  {
    ID: 5,
    FirstName: 'Rasla',
    LastName: 'McGahy',
    MobileNumber: '+08 273 745 9380',
    BloodGroup: 'B+',
    Email: 'rmcgahy4@goodreads.com',
    DateOfBirth: new Date('07-Dec-1985'),
    Gender: 'Female',
    AddressLine1: '1975 Gale Center',
    AddressLine2: '45999 South Parkway',
    City: 'Épernay',
    Country: 'France',
    ZipCode: '51209 CEDEX',
    CreatedDate: new Date('01-Dec-2016'),
    Status: 'Inactive',
    MedicalHistory: {
      Diabetes: true,
      HeartProblems: false,
      KidneyStones: true,
      Cancer: false,
      Pregnancy: false,
      HighBloodPressure: false,
      Asthma: true,
      Jaundice: false,
      HIV_AIDS: false,
      BloodThinners: true,
      HighCholestrol: true,
      KidneyDisease: true,
      RheumaticFever: false,
      Epilepsy: true,
      OtherHistory: 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',
    },
  },
  {
    ID: 6,
    FirstName: 'Isa',
    LastName: 'Duchart',
    MobileNumber: '+04 928 852 7009',
    BloodGroup: 'O+',
    Email: 'iduchart5@example.com',
    DateOfBirth: new Date('15-Mar-2008'),
    Gender: 'Female',
    AddressLine1: '45 Tennessee Circle',
    AddressLine2: '3306 Corscot Plaza',
    City: 'San Rafael',
    Country: 'Mexico',
    ZipCode: '79783',
    CreatedDate: new Date('28-Aug-1961'),
    Status: 'Active',
    MedicalHistory: {
      Diabetes: false,
      HeartProblems: true,
      KidneyStones: true,
      Cancer: true,
      Pregnancy: true,
      HighBloodPressure: true,
      Asthma: true,
      Jaundice: true,
      HIV_AIDS: true,
      BloodThinners: true,
      HighCholestrol: true,
      KidneyDisease: false,
      RheumaticFever: false,
      Epilepsy: true,
      OtherHistory: '',
    },
  },
  {
    ID: 7,
    FirstName: 'Jandy',
    LastName: 'Scandroot',
    MobileNumber: '+67 474 086 1608',
    BloodGroup: 'AB-',
    Email: 'jscandroot6@slideshare.net',
    DateOfBirth: new Date('11-Mar-1957'),
    Gender: 'Female',
    AddressLine1: '46 Algoma Hill',
    AddressLine2: '089 Birchwood Road',
    City: 'Manassas',
    Country: 'United States',
    ZipCode: '22111',
    CreatedDate: new Date('24-Jan-1989'),
    Status: 'Inactive',
    MedicalHistory: {
      Diabetes: false,
      HeartProblems: false,
      KidneyStones: false,
      Cancer: false,
      Pregnancy: true,
      HighBloodPressure: true,
      Asthma: false,
      Jaundice: true,
      HIV_AIDS: false,
      BloodThinners: false,
      HighCholestrol: false,
      KidneyDisease: false,
      RheumaticFever: false,
      Epilepsy: false,
      OtherHistory: 'Mauris lacinia sapien quis libero.',
    },
  },
  {
    ID: 8,
    FirstName: 'Meryl',
    LastName: 'Peltzer',
    MobileNumber: '+61 354 538 2161',
    BloodGroup: 'O-',
    Email: 'mpeltzer7@typepad.com',
    DateOfBirth: new Date('25-Aug-1963'),
    Gender: 'Male',
    AddressLine1: '89053 Brickson Park Way',
    AddressLine2: '13649 Iowa Lane',
    City: 'Zhangdian',
    Country: 'China',
    ZipCode: null,
    CreatedDate: new Date('22-Sep-2003'),
    Status: 'Active',
    MedicalHistory: {
      Diabetes: false,
      HeartProblems: false,
      KidneyStones: true,
      Cancer: false,
      Pregnancy: false,
      HighBloodPressure: false,
      Asthma: false,
      Jaundice: true,
      HIV_AIDS: false,
      BloodThinners: true,
      HighCholestrol: false,
      KidneyDisease: false,
      RheumaticFever: false,
      Epilepsy: true,
      OtherHistory: 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
    },
  },
  {
    ID: 9,
    FirstName: 'Hazlett',
    LastName: 'Greydon',
    MobileNumber: '+23 445 920 1173',
    BloodGroup: 'O-',
    Email: 'hgreydon8@delicious.com',
    DateOfBirth: new Date('04-Jun-1971'),
    Gender: 'Male',
    AddressLine1: '4 Bowman Crossing',
    AddressLine2: '913 Gateway Lane',
    City: 'Tres Arroyos',
    Country: 'Argentina',
    ZipCode: '2445',
    CreatedDate: new Date('01-Jan-1954'),
    Status: 'Active',
    MedicalHistory: {
      Diabetes: false,
      HeartProblems: true,
      KidneyStones: true,
      Cancer: true,
      Pregnancy: false,
      HighBloodPressure: false,
      Asthma: false,
      Jaundice: true,
      HIV_AIDS: false,
      BloodThinners: false,
      HighCholestrol: false,
      KidneyDisease: true,
      RheumaticFever: false,
      Epilepsy: true,
      OtherHistory:
        'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.',
    },
  },
  {
    ID: 10,
    FirstName: 'Marci',
    LastName: "O'Brien",
    MobileNumber: '+34 160 197 3676',
    BloodGroup: 'O+',
    Email: 'mobrien9@ibm.com',
    DateOfBirth: new Date('21-Jun-1998'),
    Gender: 'Female',
    AddressLine1: '60557 Oneill Terrace',
    AddressLine2: '4 Daystar Center',
    City: 'Laval',
    Country: 'France',
    ZipCode: '53080 CEDEX 9',
    CreatedDate: new Date('01-Jan-2003'),
    Status: 'Inactive',
    MedicalHistory: {
      Diabetes: true,
      HeartProblems: false,
      KidneyStones: true,
      Cancer: true,
      Pregnancy: false,
      HighBloodPressure: true,
      Asthma: true,
      Jaundice: false,
      HIV_AIDS: true,
      BloodThinners: false,
      HighCholestrol: false,
      KidneyDisease: false,
      RheumaticFever: true,
      Epilepsy: false,
      OtherHistory: 'Aliquam sit amet diam in magna bibendum imperdiet.',
    },
  },
];

export const Categories = [
  {
    ID: 1,
    Name: 'Category 1',
  },
  {
    ID: 2,
    Name: 'Category 2',
  },
  {
    ID: 3,
    Name: 'Category 3',
  },
  {
    ID: 4,
    Name: 'Category 4',
  },
  {
    ID: 5,
    Name: 'Category 5',
  },
  {
    ID: 6,
    Name: 'Category 6',
  },
  {
    ID: 7,
    Name: 'Category 7',
  },
];

export const Medicines = [
  {
    ID: 1,
    Name: 'Athletes Foot',
    Category: 4,
    Company: 'Target Corporation',
    Genreic: 'Terbinafine Hydrochloride',
    Group: '11673-080',
    Unit: 'mg',
    UnitPerPacking: 43,
    StroeBox: 'convallis duis',
    MinLevel: 19,
    ReOrderLevel: 92,
    Note: 'volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet',
  },
  {
    ID: 2,
    Name: 'Gabapentin',
    Category: 4,
    Company: 'Rebel Distributors Corp.',
    Genreic: 'Gabapentin',
    Group: '21695-055',
    Unit: 'ol',
    UnitPerPacking: 19,
    StroeBox: 'habitasse',
    MinLevel: 59,
    ReOrderLevel: 70,
    Note: null,
  },
  {
    ID: 3,
    Name: 'Heparin Lock Flush',
    Category: 2,
    Company: 'APP Pharmaceuticals, LLC',
    Genreic: 'HEPARIN SODIUM',
    Group: '63323-557',
    Unit: 'lt',
    UnitPerPacking: 55,
    StroeBox: 'a odio',
    MinLevel: 18,
    ReOrderLevel: 62,
    Note: 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare',
  },
  {
    ID: 4,
    Name: 'Skin Rash Complex',
    Category: 4,
    Company: 'Nova Homeopathic Therapeutics, Inc.',
    Genreic: 'Apis mellifica, Arnica montana, Belladonna, Calendula officinalis, Chelidonium majus, Echinacea angustifolia, Hepar sulphuris calcareum, Ipecacuanha, Ledum palustre, Rhus toxicodendron, Staphisagria, Urtica urens',
    Group: '52731-7023',
    Unit: 'mg',
    UnitPerPacking: 10,
    StroeBox: 'in',
    MinLevel: 66,
    ReOrderLevel: 24,
    Note: 'ac enim in tempor turpis nec euismod scelerisque quam turpis',
  },
  {
    ID: 5,
    Name: 'SPF 15',
    Category: 4,
    Company: 'Whish Body Holdings Inc',
    Genreic: 'OCTINOXATE,OXYBENZONE',
    Group: '76224-101',
    Unit: 'grm',
    UnitPerPacking: 79,
    StroeBox: 'nec dui',
    MinLevel: 13,
    ReOrderLevel: 7,
    Note: 'fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet',
  },
  {
    ID: 6,
    Name: 'Doxepin Hydrochloride',
    Category: 5,
    Company: 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC',
    Genreic: 'doxepin hydrochloride',
    Group: '49999-190',
    Unit: 'lt',
    UnitPerPacking: 12,
    StroeBox: 'pretium quis',
    MinLevel: 52,
    ReOrderLevel: 4,
    Note: null,
  },
  {
    ID: 7,
    Name: 'magiX',
    Category: 4,
    Company: 'Avon Products, Inc.',
    Genreic: 'Octisalate, Titanium Dioxide',
    Group: '10096-0265',
    Unit: 'ol',
    UnitPerPacking: 20,
    StroeBox: 'maecenas',
    MinLevel: 59,
    ReOrderLevel: 88,
    Note: 'quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum',
  },
  {
    ID: 8,
    Name: 'triple antibiotic',
    Category: 2,
    Company: 'Lake Erie Medical DBA Quality Care Products LLC',
    Genreic: 'bacitracin, neomycin, polymyxin B',
    Group: '49999-154',
    Unit: 'mg',
    UnitPerPacking: 57,
    StroeBox: 'sagittis',
    MinLevel: 42,
    ReOrderLevel: 27,
    Note: null,
  },
  {
    ID: 9,
    Name: 'Mucus Relief',
    Category: 4,
    Company: 'HyVee Inc',
    Genreic: 'Acetaminophen, Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl',
    Group: '42507-381',
    Unit: 'mg',
    UnitPerPacking: 87,
    StroeBox: 'id luctus',
    MinLevel: 72,
    ReOrderLevel: 86,
    Note: 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur',
  },
  {
    ID: 10,
    Name: 'Orchard Grass, Standardized',
    Category: 2,
    Company: 'ALK-Abello, Inc.',
    Genreic: 'Orchard Grass, Standardized',
    Group: '0268-3055',
    Unit: 'mg',
    UnitPerPacking: 20,
    StroeBox: 'morbi',
    MinLevel: 39,
    ReOrderLevel: 13,
    Note: null,
  },
];

export const Taxes = [
  {
    ID: 1,
    Name: 'GST',
    Rate: 18,
  },
  {
    ID: 2,
    Name: 'VAT',
    Rate: 10,
  },
];

export const PaymentMethods = [
  {
    ID: 1,
    Method: 'Cash',
    Status: 'Active',
  },
  {
    ID: 2,
    Method: 'Card',
    Status: 'Active',
  },
];

export const ExpenseTypes = [
  {
    ID: 1,
    Name: 'Type 1',
    Description: 'Dummy Decription',
    Status: 'Active',
  },
  {
    ID: 2,
    Name: 'Type 2',
    Description: 'Dummy Decription',
    Status: 'Inactive',
  },
];

export const Suppliers = [
  {
    ID: 1,
    Name: 'Vaidyaratnam',
    Phone: '1245678',
    Email: 'email@email.com',
    Address: '134\ndsda',
  },
];

export const ClinicalNotes = [
  {
    ID: 1,
    NoteType: 'Problem',
    Note: 'Pain while caughing',
  },
  {
    ID: 2,
    NoteType: 'Diagnosis',
    Note: 'Fever',
  },
];
